FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /usr/src/
WORKDIR /usr/src/
COPY requirements-local.txt /usr/src/

RUN apt-get update
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r requirements-local.txt